<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hehe.proto

namespace Fanhehe\Hehe;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Test extends \Google\Protobuf\Internal\Message
{
    private $id = 0;
    private $name = '';

    public function getId()
    {
        return $this->id;
    }

    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

}

class Test_gender
{
    const MALE = 0;
    const FEMAILE = 1;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a650a0a686568652e70726f746f120c66616e686568652e686568652241" .
    "0a0454657374120a0a026964180120012805120c0a046e616d6518022001" .
    "2809221f0a0667656e64657212080a044d414c451000120b0a0746454d41" .
    "494c451001620670726f746f33"
));

